package com.trustfund.model;

public enum NotificationType {
    NEW_MESSAGE,
    DONATION_SUCCESS,
    SOCIAL_INTERACTION,
    FLAG_DECISION,
    KYC_DECISION,
    CAMPAIGN_APPROVAL,
    APPOINTMENT_STATUS,
    APPOINTMENT_REMINDER,
    CAMPAIGN_UPDATE,
    EXPENDITURE_DECISION,
    WITHDRAWAL_STATUS,
    EVIDENCE_DECISION
}
